### ISSUE TITLE
Pass max permitted tensor value on Transforms

### ISSUE THREAD

**Issue by datumbox** [pmeier/torchvision-datasets-rework#3]
Since this repo restructures not only datasets but also transforms, it's worth adding a note concerning a potential extension discussed in the past.

Some transforms require knowing the maximum value of the image. Our current implementation has some [voodoo code](https://github.com/pytorch/vision/blob/96f6e0a117d5c56f7e0237851dbb96144ebb110b/torchvision/transforms/functional_tensor.py#L840) to determine the value from the dtype. Here is a list of transforms that explicitly or implicitly make such assumptions:

- autocontrast
- adjust_hue
- adjust_brightness
- adjust_contrast
- adjust_saturation
- adjust_sharpness
- invert
- equalize
- adjust_gamma
- resize

This brings a bunch of assumptions that we try to phase out, for example that if an image is float it's assumed that it was normalized to 0-1 using the `to_tensor`.

One solution to this problem is to allow the user to pass the max value on the Functional or Class transform. This would work similar to `fill` attribute that we already support for some transforms. It's possible to make it BC by having a default None value that leads to auto-detection similar to what we do now.

An alternative could also be to read the value from the meta data of `Image`.

**Comment by pmeier** [comment]
> An alternative could also be to read the value from the meta data of `Image`.

I think this is the superior approach. We can simply have a `min_value` and `max_value` (names up for discussion) properties on an `Image`, that will be filled by default with the same rules we currently have, i.e. `[0, 1]` for floating point dtypes and `[0, torch.iinfo(dtype).max]` for integral ones. By using this attribute, the transforms would stay decoupled from the actual data, which is preferable.
